# -*- coding: utf-8 -*-
"""STML LAB 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-_KYjZ8PD6RJhyymJawQ7tZFox5GfRw

@Author Himesh

**1st Question**
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

"""importing data set"""

data1=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Salary_Data.csv")
data1.head()

"""constructing data frame using pandas"""

df1=pd.DataFrame(data1)
df1

"""Features(x) & Target(y)"""

x=df1['YearsExperience']
y=df1['Salary']

"""plotting data using scatter plot"""

plt.scatter(x,y)
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.show

"""Normalizing data"""

scaler=MinMaxScaler()
normalized=scaler.fit_transform(df1)
normalized=pd.DataFrame(normalized,columns=df1.columns)
normalized.head()

"""**2nd Question**"""

data2=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes_data_upload.csv")
df2=pd.DataFrame(data2)

"""Features and target"""

x1=df2.drop("class",axis=1)
y1=df2['class']
x1,y1

"""replacing strings with numericals"""

replaced=data2.replace({"No":0,"Yes":1,"Male":1,"Female":0,'Positive':1,'Negative':0})
replaced.head()